###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email":"abc@gmail.com",
    "password":"123456"
}

###
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "email":"abc@gmail.com",
    "password":"123456"
}

###
POST http://localhost:3000/api/auth/checkemail
content-type: application/json

{
    "email":"abc@gmail.com"
}


###
GET http://localhost:3000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRUZFhsb0hXOWFzN0VSVkR1VU40ell1aEpPaEpMQ1BBeHp1OVY0OWp3OFRqblhwbHRRYUJWMiIsImlhdCI6MTYxNzkzNzg0OX0.x5XENQYoDX9EagVevI2zZrTr0CsIhppNaIHh8r75Ra0

###

GET http://localhost:3000/api/cards/607364016bd55069f43d0bd0/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhYmNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeW02L3ZNdGZzNW1pdXhFYmJwWjI1T0dCUkg1QlNyUmVILzlTclRLT2R3UThHU3B5eFdRQk8iLCJpYXQiOjE2MTgxNzExMzB9.j4QFLq0pzf5uy_eNspg8cv8MvzhTw9D46_8sEmIxyAU


###

POST http://localhost:3000/api/cards/607364016bd55069f43d0bd0/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhYmNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeW02L3ZNdGZzNW1pdXhFYmJwWjI1T0dCUkg1QlNyUmVILzlTclRLT2R3UThHU3B5eFdRQk8iLCJpYXQiOjE2MTgxNzExMzB9.j4QFLq0pzf5uy_eNspg8cv8MvzhTw9D46_8sEmIxyAU

{
    "title": "pushing cards to db",
    "order": 2,
    "description": "this card added via rest cleint",
    "label": "mwa_project",
    "deadline": "04/13/2021"
}

###

PATCH http://localhost:3000/api/cards/607378398ebc402a7842dc8e/607364016bd55069f43d0bd0/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhYmNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeW02L3ZNdGZzNW1pdXhFYmJwWjI1T0dCUkg1QlNyUmVILzlTclRLT2R3UThHU3B5eFdRQk8iLCJpYXQiOjE2MTgxNzExMzB9.j4QFLq0pzf5uy_eNspg8cv8MvzhTw9D46_8sEmIxyAU

{
    "title": "updating cards to db",
    "order": 222,
    "description": "this card updated via rest cleint",
    "label": "mwa_project",
    "deadline": "04/13/2021"
}
###

DELETE http://localhost:3000/api/cards/60737a89b8b2c431209c1c5c/607364016bd55069f43d0bd0/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhYmNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeW02L3ZNdGZzNW1pdXhFYmJwWjI1T0dCUkg1QlNyUmVILzlTclRLT2R3UThHU3B5eFdRQk8iLCJpYXQiOjE2MTgxNzExMzB9.j4QFLq0pzf5uy_eNspg8cv8MvzhTw9D46_8sEmIxyAU

###  Add new column (http://localhost:3000/api/columns/:board_id)
POST http://localhost:3000/api/columns/60735ffe1bbf604c9449a893
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhaG1hZEBob3RtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEFsUkIyUC52ZGFRSXZvVDMwcy9xUGUxVVQzS3daWlZMM1R0eGlRLm80UVBPb2V4LklXeFAyIiwiaWF0IjoxNjE4MTczMTA3fQ.dsI8Ye4eZGz5M6fFPM3Qz0Q5iMpZ7J9pDs3djb2trK4

 { 
            "name": "TEST",
            "order": 1,
            "cards": [
                {
                    "_id": 3,
                    "title": "doing homework 1",
                    "order": 1,
                    "description": "this is the content of a card",
                    "label": "tag name",
                    "column": "column_name",
                    "board": "board_name",
                    "deadline": "01/01/2022",
                    "created_date": "01/01/2022",
                    "updated_date": "01/01/2022"

                }
            ]
}

### Edit column name (http://localhost:3000/api/columns/:column_id/:board_id)
PATCH http://localhost:3000/api/columns/60736b8cdfb65a3124376591/60735ffe1bbf604c9449a893
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhaG1hZEBob3RtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEFsUkIyUC52ZGFRSXZvVDMwcy9xUGUxVVQzS3daWlZMM1R0eGlRLm80UVBPb2V4LklXeFAyIiwiaWF0IjoxNjE4MTczMTA3fQ.dsI8Ye4eZGz5M6fFPM3Qz0Q5iMpZ7J9pDs3djb2trK4
{
    "name" : "Name changed"
}

###